version: "3.1"

services:
  mongodb:
    image: mongo
    # restart: always # Para que automáticamente reinicio
    environment:
      MONGO_INITDB_DATABASE: authdb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ./dist:/data/db
    ports:
      - 27017:27017